#Demo / example parameter file for phyloGenerator2
# - The gene section is nested: there is one entry for each gene,
#         and each gene has its own options
# - Not all of the options are turned on;
#         uncomment sections to try them out

#Start of options

######################
#BASICS###############
######################
#Species list
species: /home/will/Code/phyloGenerator2/demo/species.txt
#Output directry (must aready exist)
working_dir: /home/will/test/
#Email address for downloads
email: will.pearse@gmail.com

######################
#DNA DOWNLOAD#########
######################
#Each gene has its own section
#gap_length and max_gaps are only required if
#  performing secondary DNA check (:hawkeye=>true)
genes:
  rbcL:
    ref_file: /home/will/Code/phyloGenerator2/demo/rbcL_reference.fasta
    ref_min: 700
    ref_max: 1600
    gap_length: 20
    max_gaps: 10
    max_dwn: 10
  matK:
    ref_file: /home/will/Code/phyloGenerator2/demo/rbcL_reference.fasta
    ref_min: 400
    ref_max: 1500
    gap_length: 5
    max_gaps: 10
    max_dwn: 10
      
######################
#OPTIONS##############
######################
# - with the exception of 'phy_method' none of these must be given
# - there is no 'false' value that must be supplied
#Which program to use for phylogenetic search
#phy_method: examl
phy_method: raxml
#phy_method: exabayes
#Whether to perform secondary check of sequences
#hawkeye: true
#Constraint tree
#constraint: /home/will/Code/phyloGenerator2/demo/constraint.tre
#Whether to fit different DNA models for each gene ('partitions')
partition: true
#Whether to load DNA data from a previous run ('cached' run)
#cache: /home/will/test
